<<<<<<< HEAD
pdjd_shop:
    resource: "@pdjdShopBundle/Resources/config/routing.yml"
    prefix:   /

=======
app:
    resource: @AppBundle/Controller/
    type:     annotation
>>>>>>> 2051e73fe41b414fd3ae3aad814d3a2c51cc9c2e
